### ISSUE TITLE
Let's get this online!

### ISSUE THREAD

**Issue by revan** [roopeshkom/RUCourseMaps#1]
Awesome job again, guys. But let's get this hosted!

You might consider using [OpenShift](https://www.openshift.com/pricing/index.html) instead of Heroku. It's a similar service, but their free tier gives you more (your app will only sleep after 24 hours, not 30 minutes).

There's a guide on deploying Flask apps [here](https://developers.openshift.com/languages/python/flask.html), it basically boils down to:
- [ ] Get your dependencies sorted out and listed in a `requirements.txt`
- [ ] Install their `rhc` tool, run a couple commands and edit one file

The dependencies thing means you'll want to figure out the venv again. I'd recommend deleting it from the repository (venvs aren't supposed to be shared like that) and starting a new one. It _should_ (fingers crossed) be as simple as

```
$ virtualenv create venv
$ source venv/bin/activate
$ pip install beautifulsoup4
$ pip install flask
$ pip freeze > requirements.txt
```

Let me know if you need anything!

**Comment by BTruer** [comment]
Hey Revan! Thank you for this guide. We are working on getting this deployed specifically cleaning up the file structure and dependencies. Thanks for the help! We will notify you and the fb gorup/ r/reddit as soon as it is complete. Thanks again!

**Comment by adidalal** [comment]
Should also update your `.gitignore`: https://www.gitignore.io/api/python is a solid template

Make sure to delete the venv folder and force push so you don't have it as part of your source on github.

**Comment by revan** [comment]
+1 to adding the `.gitignore`, but I think deleting the venv folder from the history is a bit more complicated than just a force push. Just a regular `git rm -rf venv` is probably enough.

Again, let me know if you guys need any advice!

**Comment by BTruer** [comment]
https://github.com/BTruer/RUCM
https://rucm.herokuapp.com/
